# Generated by Django 3.1.2 on 2022-02-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_raw_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='especial',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='especial',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='region',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
