# Generated by Django 3.1.2 on 2022-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20220208_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
