# Generated by Django 3.1.2 on 2022-02-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20220214_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='tuvo_problema',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
